  "is_halal" boolean,
  "open_time" int,
  "close_time" int,
  "current_location"  geography(Point, 4326);
  "created_at" timestamp,
  "store_image_url" varchar(255)
);

CREATE TABLE gerobakku."master_categories" (
  "category_id" int PRIMARY KEY,
  "name" varchar(255)
);

CREATE TABLE gerobakku."menu_items" (
  "item_id" int PRIMARY KEY,
  "store_id" int,
  "name" varchar(255),
  "description" text,
  "price" float,
  "is_available" boolean,
  "menu_image_url" varchar(255),
  "created_at" timestamp
);

CREATE TABLE gerobakku."transactional_reviews" (
  "rating_id" int PRIMARY KEY,
  "customer_id" int,
  "store_id" int,
  "score" int,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE gerobakku."transactional_favorites" (
  "customer_id" int,
  "store_id" int,
  PRIMARY KEY ("customer_id", "store_id")
);

CREATE TABLE gerobakku."transactional_wishlist_items" (
  "customer_id" int,
  "item_id" int,
  PRIMARY KEY ("customer_id", "item_id")
);

CREATE TABLE gerobakku."transactional_store_location" (
	location_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	store_id int4 NULL,
	created_at timestamptz DEFAULT now() NULL,
	"location" extensions.geography(point, 4326) NULL,
	CONSTRAINT transactional_store_location_pkey PRIMARY KEY (location_id),
	CONSTRAINT transactional_store_location_store_id_fkey FOREIGN KEY (store_id) REFERENCES gerobakku.stores(store_id) ON DELETE CASCADE
);

CREATE TABLE gerobakku."transactional_messages" (
  "message_id" int PRIMARY KEY,
  "sender_id" int,
  "receiver_id" int,
  "content" text,
  "sent_at" timestamp,
  "is_read" boolean
);

ALTER TABLE gerobakku."customers" ADD FOREIGN KEY ("user_id") REFERENCES gerobakku."users" ("user_id");

ALTER TABLE gerobakku."customers" ADD FOREIGN KEY ("category_preference") REFERENCES gerobakku."master_categories" ("category_id");

ALTER TABLE gerobakku."vendors" ADD FOREIGN KEY ("user_id") REFERENCES gerobakku."users" ("user_id");

ALTER TABLE gerobakku."stores" ADD FOREIGN KEY ("vendor_id") REFERENCES gerobakku."vendors" ("vendor_id");

ALTER TABLE gerobakku."stores" ADD FOREIGN KEY ("category_id") REFERENCES gerobakku."master_categories" ("category_id");

ALTER TABLE gerobakku."menu_items" ADD FOREIGN KEY ("store_id") REFERENCES gerobakku."stores" ("store_id");

ALTER TABLE gerobakku."transactional_reviews" ADD FOREIGN KEY ("customer_id") REFERENCES gerobakku."customers" ("customer_id");

ALTER TABLE gerobakku."transactional_reviews" ADD FOREIGN KEY ("store_id") REFERENCES gerobakku."stores" ("store_id");

ALTER TABLE gerobakku."transactional_favorites" ADD FOREIGN KEY ("customer_id") REFERENCES gerobakku."customers" ("customer_id");

ALTER TABLE gerobakku."transactional_favorites" ADD FOREIGN KEY ("store_id") REFERENCES gerobakku."stores" ("store_id");

ALTER TABLE gerobakku."transactional_wishlist_items" ADD FOREIGN KEY ("customer_id") REFERENCES gerobakku."customers" ("customer_id");

ALTER TABLE gerobakku."transactional_wishlist_items" ADD FOREIGN KEY ("item_id") REFERENCES gerobakku."menu_items" ("item_id");

ALTER TABLE gerobakku."transactional_messages" ADD FOREIGN KEY ("sender_id") REFERENCES gerobakku."users" ("user_id");

ALTER TABLE gerobakku."transactional_messages" ADD FOREIGN KEY ("receiver_id") REFERENCES gerobakku."users" ("user_id");

.